name: Python application

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: ${{ env.pythonLocation }}
        key: LOCATION-${{ env.pythonLocation }}-SETUP-${{ hashFiles('setup.py') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[dev]'

    - name: Linting with flake8
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
